---

- name: Deploy ISE Nodes
  hosts: ISE
  gather_facts: no
  vars_files:
    - vars/main.yaml
  vars:
    ise_hostname: "{{ inventory_hostname }}"
    ise_username: "{{ lookup('env','ISE_REST_USERNAME') | default( ise.defaults.rest.username ) }}"
    ise_password: "{{ lookup('env','ISE_REST_PASSWORD') | default( ise.defaults.rest.password ) }}"
    ise_verify:   "{{ lookup('env','ISE_VERIFY') | default( ise.defaults.security.verify ) | default(True) }}"
    ise_debug:    "{{ lookup('env','ISE_DEBUG')  | default( ise.defaults.platform.debug )  | default(False) }}"
  tasks:

  - name: Show ISE Node Deployment Status
    ansible.builtin.include_tasks: tasks/ise/node_deployment.yaml

  - name: Add your own ...
    ansible.builtin.debug:
      msg: Add your own tasks for deploying ISE ...

...
