---

- name: Deploy ISE Nodes
  hosts: ISE
  gather_facts: no
  vars_files: vars/main.yaml
  tasks:

  - name: Show ISE Environment Setup
    ansible.builtin.include_tasks: tasks/ise/environment_valid.yaml

  - name: Wait for ISE Application Server
    ansible.builtin.include_tasks: tasks/ise/wait_for_app_server.yaml

  - name: Enable ISE APIs
    ansible.builtin.include_tasks: tasks/ise/apis_enabled.yaml

  - ansible.builtin.debug: var=ISE

  - name: Get ISE Facts for the Deployment
    # loop: "{{ ISE }}"
    ansible.builtin.include_tasks: tasks/ise/facts.yaml

  # - name: Show ISE Node Deployment Status
  #   ansible.builtin.include_tasks: tasks/ise/node_deployment.yaml

  - name: Add your own tasks for deploying ISE ...
    ansible.builtin.debug:
      msg: Add your own tasks for deploying ISE ...


...