---

- name: Wait for ISE
  hosts: ISE
  gather_facts: no
  vars_files:
    - vars/main.yaml
  vars:
    ise_hostname: "{{ inventory_hostname }}"
    ise_username: "{{ lookup('env','ISE_REST_USERNAME') | default('iseadmin', true) }}"
    ise_password: "{{ lookup('env','ISE_REST_PASSWORD') | default('ISEisC00L!', true) }}"
    ise_verify:   "{{ lookup('env','ISE_VERIFY') | default(False, true) }}"
    ise_debug:    "{{ lookup('env','ISE_DEBUG')  | default(False, true) }}"
  tasks:


  - name: Wait for ISE Application Server
    ansible.builtin.include_tasks: tasks/ise/wait_for_app_server.yaml

  - name: Enable ISE APIs
    ansible.builtin.include_tasks: tasks/ise/apis_enabled.yaml

  - name: Show ISE Facts
    ansible.builtin.include_tasks: tasks/ise/set_facts.yaml

  - name: Show ISE Node Deployment Status
    ansible.builtin.include_tasks: tasks/ise/node_deployment.yaml


...
