---

- name: Wait for ISE
  hosts: ise_in_aws  # all instances with project name "ise_in_aws"
  gather_facts: no
  vars_files:
    - vars/main.yaml
  tasks:


  - name: Show ISE Environment Setup
    ansible.builtin.include_tasks: tasks/ise/environment_valid.yaml

  - name: Wait for ISE Application Server
    ansible.builtin.include_tasks: tasks/ise/wait_for_app_server.yaml

  - name: Enable ISE APIs
    ansible.builtin.include_tasks: tasks/ise/apis_enabled.yaml

  - name: Show ISE Facts
    ansible.builtin.include_tasks: tasks/ise/facts.yaml

  - name: Show ISE Node Deployment Status
    ansible.builtin.include_tasks: tasks/ise/node_deployment.yaml


...
