---
#------------------------------------------------------------------------------
# To use the `aws_ec2` dynamic inventory plugin, add this entry to the
# ansible.cfg file's [defaults] section :
#   [defaults]
#   inventory=inventory/aws_ec2.yaml
# ⚠ This file must end with `aws_ec2.y[a]ml`
#
# You may verify that it works with the command
#   `ansible-inventory --graph [-i inventory/aws_ec2.yaml]`
#
# For more examples, see
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
#------------------------------------------------------------------------------


plugin: amazon.aws.aws_ec2

aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"

# 💡 Save time and explicitly list only your regions!
regions:
# - eu-north-1
# - ap-south-1
# - eu-west-3
# - eu-west-2
# - eu-west-1
# - ap-northeast-3
# - ap-northeast-2
# - ap-northeast-1
# - sa-east-1
# - ca-central-1
# - ap-southeast-1
# - ap-southeast-2
# - eu-central-1
# - us-east-1
# - us-east-2
- us-west-1
# - us-west-2

filters:
  # instance-state-name: ['running']
  # tag:product: ISE

strict: False

# groups:
#   redhat: "'redhat' in tags.os"
#   ubuntu: "'ubuntu' in tags.os"

keyed_groups:
- key: tags
  prefix: tag
  separator: '_'
- key: tags.Name
  # prefix: name_
  separator: ''
- key: tags.product   # or tags['product']
  prefix: product
  separator: ''
- key: tags.project   # or tags['project']
  prefix: project
  separator: ''
- key: tags.services
  prefix: service
  separator: ''
- key: tags.roles
  prefix: role
  separator: ''
- key: placement.availability_zone
  prefix: az
  separator: '_'
- key: placement.group
  # prefix: group
  separator: ''
- key: placement.region      # group per region e.g. region_us_east_2
  prefix: region
  separator: '_'
- key: instance_type
  # prefix: type
  separator: ''

# Controls the Ansible `inventory_hostname` value
# Default is the public DNS name
# List in order of precedence for hostname variables
hostnames:
- tag:Name
- ip-address
- dns-name
# - private-ip-address

# Set individual variables with compose
compose:
  ansible_host: public_ip_address  # Use private IP address to connect to the host
  ansible_host: private_ip_address  # Use private IP address to connect to the host
  # inventory_hostname: private_ip_address  # Use private IP address to connect to the host
  # ansible_host: name  # Use name to connect to the host
  # ansible_host: public_dns_name

...