---
#
# Uses ansible.builtin.shell to get a timestamp from the OS `date` utility.
#
# Using `ansible_data_time` requires you to enable `gather_facts`
# and only captures the time at the start of the playbook.
#

  - name: Get time in seconds since Unix Epoch
    delegate_to: localhost
    ansible.builtin.shell: "date +%s"
    tags: timestamp,ts
    register: seconds

  - name: date in seconds
    delegate_to: localhost
    ansible.builtin.set_fact:
      seconds: "{{ seconds.stdout }}"
    tags: timestamp,ts


  - name: Timestamp String
    delegate_to: localhost
    vars:
      format: "+%Y-%m-%d-%H-%M-%S-%Z"   # YYYY-MM-DD-hh-mm-ss-ZZZ
    ansible.builtin.shell: "date -jr {{ seconds }} {{ format }}"
    register: timestamp_string
    tags: timestamp,ts


  - name: Set timestamp elements
    ansible.builtin.set_fact:
      timestamp:
        seconds: "{{ seconds }}"  # seconds since the Unix epoch
        year:    "{{ timestamp_string.stdout[0:4]}}"   # YYYY
        month:   "{{ timestamp_string.stdout[5:7]}}"   # MM
        day:     "{{ timestamp_string.stdout[8:10]}}"  # DD
        hour:    "{{ timestamp_string.stdout[11:13]}}" # hh
        minute:  "{{ timestamp_string.stdout[14:16]}}" # mm
        second:  "{{ timestamp_string.stdout[17:19]}}" # ss
        tz:      "{{ timestamp_string.stdout[20:24]}}" # ZZZ
    tags: timestamp,ts


  - name: Set timestamp.date
    ansible.builtin.set_fact:
      # ISO8601 Date: YYYY-MM-DD
      timestamp: "{{ timestamp | combine ( { 'date' : timestamp.year+'-'+timestamp.month+'-'+timestamp.day } ) }}"
    tags: timestamp,ts

  - name: Set timestamp.time
    ansible.builtin.set_fact:
      # ISO8601 Time: hh:mm:ss
      timestamp: "{{ timestamp | combine ( { 'time' : timestamp.hour+':'+timestamp.minute+':'+timestamp.second } ) }}"
    tags: timestamp,ts

  - name: Set timestamp.datetime
    ansible.builtin.set_fact:
      # Date and Time (local): '2022-04-24T16:27:33'
      timestamp: "{{ timestamp | combine ( { 'datetime' : timestamp.year+'-'+timestamp.month+'-'+timestamp.day+'T'+timestamp.hour+':'+timestamp.minute+':'+timestamp.second } ) }}"
    tags: timestamp,ts


  - name: "{{ label }}"
    ansible.builtin.debug:
      msg: "{{ timestamp.datetime }}"
    tags: timestamp,ts


...
