#
# ISE Deployemnt for thomas in AWS
#

ise_nodes:
- name: ise-1
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge    # ISE Eval/Demo size
  private_ip: 172.31.2.11
  roles:
  - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services:
  - DeviceAdmin
  - Profiler
  - pxGrid
  - pxGridCloud
  - Session
  - PassiveIdentity
  - SXP
  - TC-NAC

- name: ise-2
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge    # ISE Eval/Demo size
  private_ip: 172.31.2.12
  roles:
  - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services:
  - DeviceAdmin
  - Profiler
  - pxGrid
  - pxGridCloud
  - Session
  - PassiveIdentity
  - SXP
  - TC-NAC


# - name: ise-32-t3xlarge
#   ami: ami-0926779d4f3f1e54a  # us-west-1 ISE 3.2.0.366 20220601
#   instance_type: t3.xlarge    # ISE Eval/Demo size
#   private_ip: 172.31.2.13
#   roles:
#   - Standalone
#   # - PrimaryAdmin
#   # - PrimaryMonitoring
#   # - SecondaryAdmin
#   # - SecondaryMonitoring
#   # - PrimaryDedicatedMonitoring
#   # - SecondaryDedicatedMonitoring
#   services:
#   - DeviceAdmin
#   - Profiler
#   - pxGrid
#   - pxGridCloud
#   - Session
#   - PassiveIdentity
#   - SXP
#   - TC-NAC


# - name: ise-32-c54xlarge
#   ami: ami-0926779d4f3f1e54a  # us-west-1 ISE 3.2.0.366 20220601
#   instance_type: c5.4xlarge
#   private_ip: 172.31.2.14
#   roles:
#   - Standalone
#   # - PrimaryAdmin
#   # - PrimaryMonitoring
#   # - SecondaryAdmin
#   # - SecondaryMonitoring
#   # - PrimaryDedicatedMonitoring
#   # - SecondaryDedicatedMonitoring
#   services:
#   - DeviceAdmin
#   - Profiler
#   - pxGrid
#   - pxGridCloud
#   - Session
#   - PassiveIdentity
#   - SXP
#   - TC-NAC