#------------------------------------------------------------------------------
# ISE Small Deployment (2 nodes)
#------------------------------------------------------------------------------

ise_nodes:
- name: ise-1
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  public_dns_name:  "ise-primary.{{ domain_name }}"
  # private_dns_name: "ise-ppan.{{ domain_name }}"
  private_ip: 172.31.2.11
  roles:
  # - Standalone
  - PrimaryAdmin
  - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services:
  - DeviceAdmin
  - Profiler
  - Session
  - pxGrid
  - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

- name: ise-2
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  public_dns_name:  "ise-secondary.{{ domain_name }}"
  # private_dns_name: "ise-span.{{ domain_name }}"
  private_ip: 172.31.2.12
  roles:
  # - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  - SecondaryAdmin
  - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services:
  - DeviceAdmin
  - Profiler
  - Session
  - pxGrid
  - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

#
# Optional third node for for HA Failover or extra PSN
#
- name: ise-3
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  public_dns_name:  "ise-psn.{{ domain_name }}"
  # private_dns_name: "ise-span.{{ domain_name }}"
  private_ip: 172.31.2.13
  roles:
  # [] (no roles) for dedicated PSN
  # - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services:
  - DeviceAdmin
  - Profiler
  - Session
  - pxGrid
  - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

