---
#------------------------------------------------------------------------------
# ISE Large Deployment
# - ise-ppan
# - ise-span
# - ise-pmnt
# - ise-smnt
# - ise-psn-1
# - ise-psn-2
# - ise-pxg-1
# - ise-pxg-2
#------------------------------------------------------------------------------

ise_nodes:
- name: ise-ppan
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.11
  roles:
  # - Standalone
  - PrimaryAdmin
  # - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services: []    # use [] (no services) for dedicated PAN/MNT

- name: ise-span
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.12
  roles:
  # - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services: []    # use [] (no services) for dedicated PAN/MNT

- name: ise-pmnt
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.13
  roles:
  # - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services: []    # use [] (no services) for dedicated PAN/MNT

- name: ise-smnt
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.14
  roles:
  # - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  - SecondaryDedicatedMonitoring
  services: []    # use [] (no services) for dedicated PAN/MNT

#
# PSNs
#

- name: ise-psn-1
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.21
  roles: []   # use [] (no roles) for dedicated PSN
  services:
  - DeviceAdmin
  - Profiler
  - Session
  # - pxGrid
  # - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

- name: ise-psn-2
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.22
  roles: []   # use [] (no roles) for dedicated PSN
  services:
  - DeviceAdmin
  - Profiler
  - Session
  # - pxGrid
  # - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

- name: ise-pxg-1
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.23
  roles: []   # use [] (no roles) for dedicated PSN
  services:
  # - DeviceAdmin
  # - Profiler
  # - Session
  - pxGrid
  - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

- name: ise-pxg-2
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.24
  roles: []   # use [] (no roles) for dedicated PSN
  services:
  # - DeviceAdmin
  # - Profiler
  # - Session
  - pxGrid
  - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

