---
#------------------------------------------------------------------------------
# ISE Medium Deployment
# - ise-ppan
# - ise-span
# - ise-psn-1
# - ise-psn-2
#------------------------------------------------------------------------------

ise_nodes:
- name: ise-ppan:
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.11
  roles:
  # - Standalone
  - PrimaryAdmin
  - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services: []    # use [] (no services) for dedicated PAN/MNT

- name: ise-span:
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.12
  roles:
  # - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  - SecondaryAdmin
  - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  services: []    # use [] (no services) for dedicated PAN/MNT

- name: ise-psn-1:
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.21
  roles: []   # use [] (no roles) for dedicated PSN
  services:
  - DeviceAdmin
  - Profiler
  - pxGrid
  - pxGridCloud
  - Session
  # - PassiveIdentity
  # - SXP
  # - TC-NAC

- name: ise-psn-2:
  ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  instance_type: t3.xlarge
  private_ip: 172.31.2.22
  roles: []   # use [] (no roles) for dedicated PSN
  services:
  - DeviceAdmin
  - Profiler
  - pxGrid
  - pxGridCloud
  - Session
  # - PassiveIdentity
  # - SXP
  # - TC-NAC


...