#------------------------------------------------------------------------------
# Standalone ISE Node
# See https://cs.co/ise-aws for available AWS Instance Types and hourly rates
#------------------------------------------------------------------------------

ise_nodes:
- name: ise
  # ami: ami-0965fef2e601ad4d0  # us-west-1 ISE 3.1 Patch 1 20211209
  ami: ami-0c59bbc144f97a440  # us-west-1 ISE 3.2.0.542 20221002
  instance_type: t3.xlarge    # Evaluation/Demo only
  volume_size: 300
  private_ip: 172.31.2.11
  # roles:       # use [] (no roles) for dedicated PSN
  # - Standalone
  # - PrimaryAdmin
  # - PrimaryMonitoring
  # - SecondaryAdmin
  # - SecondaryMonitoring
  # - PrimaryDedicatedMonitoring
  # - SecondaryDedicatedMonitoring
  # services:    # use [] (no services) for dedicated PAN/MNT
  # - DeviceAdmin
  # - Profiler
  # - Session
  # - pxGrid
  # - pxGridCloud
  # - PassiveIdentity
  # - SXP
  # - TC-NAC