---
#------------------------------------------------------------------------------
# Sets facts for ISE in an `ise_facts` variable.
# Example:
# ise_facts:
#   ise:
#     fqdn: ise.securitydemo.net
#     host: 198.18.133.27
#     hostname: ise
#     ...
#   ise-2:
#     ...
#   ise-3:
#   ...
#------------------------------------------------------------------------------

  # Combine() all dictionary attributes into `ise_facts`
  # then add to `ise_facts` at the end
  - name: Create ise_facts Dictionary
    ansible.builtin.set_fact:
      ise_facts: {}

  - name: Get Node Info
    cisco.ise.node_info:
      ise_hostname: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
    register: node_info
  # - ansible.builtin.debug: var=node_info
  #
  # node_info:
  #   changed: false
  #   failed: false
  #   ise_response:
  #     displayName: ise
  #     fqdn: ise.securitydemo.net
  #     gateWay: 198.18.128.1
  #     id: a91a15f0-78a8-11eb-b987-005056aba98b
  #     inDeployment: false
  #     ipAddress: 198.18.133.27
  #     ipAddresses:
  #     - 198.18.133.27
  #     ipV6Addresses: []
  #     link:
  #       href: https://198.18.133.27/ers/config/node/name/ise
  #       rel: self
  #       type: application/json
  #     name: ise
  #     nodeServiceTypes: SESSION,PROFILER
  #     otherPapFqdn: ''
  #     papNode: true
  #     primaryPapNode: false
  #     pxGridNode: false
  #     sxpIpAddress: ''
  #   result: ''
  #


  - name: Get Node Deployment Info
    cisco.ise.node_deployment_info:
      ise_hostname: "{{ ansible_host }}"
      hostname: "{{ inventory_hostname }}"
    register: node_deployment_info
  # - ansible.builtin.debug: var=node_deployment_info
  #
  # node_deployment_info:
  #   changed: false
  #   failed: false
  #   ise_response:
  #     fqdn: ise.securitydemo.net
  #     hostname: ise
  #     ipAddress: 198.18.133.27
  #     nodeStatus: Connected
  #     roles:
  #     - Standalone
  #     services:
  #     - Session
  #     - Profiler
  #   result: ''
  #


  #----------------------------------------------------------------------------
  # ISE Version and Patch(es)
  #----------------------------------------------------------------------------
  # 🛑 cisco.ise.node_facts is flaky with random [500] Internal Server Errors
  # 🛑 The `/ers/config/op/systemconfig/iseversion` API endpoint is slow,
  #    unreliable, and the response format is complicated.
  # 💡 Use cisco.ise.patch_info for ISE Version info with ISE 3.1P1+
  #----------------------------------------------------------------------------

  - name: Get Patch Info
    cisco.ise.patch_info:
      ise_hostname: "{{ ansible_host }}"
    register: patch_info
  # - ansible.builtin.debug: var=patch_info
  #
  # patch_info:
  #   changed: false
  #   failed: false
  #   ise_response:
  #     iseVersion: 3.1.0.518
  #     patchVersion:
  #     - installDate: Mon Dec 13 21:49:27 2021
  #       patchNumber: 1
  #   result: ''
  #

  - name: Set ISE Version
    when: patch_info is defined
    ansible.builtin.set_fact:
      version: "{{ patch_info.ise_response.iseVersion }}"

  - name: Get Hotpatch Info
    cisco.ise.hotpatch_info:
      ise_hostname: "{{ ansible_host }}"
    register: hotpatch_info
  # - ansible.builtin.debug: var=hotpatch_info
  #
  # hotpatch_info:
  #   changed: false
  #   failed: false
  #   ise_response:
  #   - hotpatchName: CSCwa47133_3.1.0.518_patch1
  #     installDate: ' '
  #   result: ''
  #

  - name: Create Additional Attributes
    ansible.builtin.set_fact:
      attributes:
        ip_address: "{{ node_info.ise_response.ipAddress }}"
        version: "{{ version }}"
        version_major: "{{ version.split('.')[0] }}"
        version_minor: "{{ version.split('.')[1] }}"
        version_release: "{{ version.split('.')[2] }}"
        version_build: "{{ version.split('.')[3] }}"
        is_2x: "{{ version.split('.')[0] | int == 2 }}"
        is_3x: "{{ version.split('.')[0] | int == 3 }}"
        unpatched:  "{{ patch_info.ise_response.patchVersion | count == 0 }}"

  - name: Combine Multiple Dictionaries into `ise_facts`
    ansible.builtin.set_fact:
      ise_facts : "{{ ise_facts
        | combine( node_info.ise_response )
        | combine( node_deployment_info.ise_response )
        | combine( { 'version'    : patch_info.ise_response.iseVersion } )
        | combine( { 'patches'    : patch_info.ise_response.patchVersion } )
        | combine( { 'hotpatches' : hotpatch_info.ise_response } )
        | combine( attributes )
        }}"

  - name: Remove `link` from ise_facts
    ansible.builtin.set_fact:
      ise_facts: "{{ ise_facts | dict2items | rejectattr('key', 'eq', 'link') | list | items2dict }}"

  # - name: Add {{ inventory_hostname }} to ise_facts
  #   ansible.builtin.set_fact:
  #     # ise_facts : "{{ ise_facts | default({}) | combine( { inventory_hostname : ise_facts } ) }}"
  #     ise_facts : "{{ ise_facts | default({}) | combine( { inventory_hostname : ise_facts } ) }}"

  # - ansible.builtin.debug: var=ise_facts


...