---
- name: ISE Node Deployment Info
  delegate_to: localhost
  cisco.ise.node_deployment_info:
    ise_hostname: "{{ ansible_host }}"
    hostname: "{{ inventory_hostname }}"
  register: node_info

- ansible.builtin.debug: var=node_info
