---
- name: Wait for ISE SSH
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 22
    state: started # started == Port is open
    delay: 0 # Default: 0. Seconds before first check
    sleep: 10 # Default: 1. Seconds between checks
    timeout: 1800 # Default: 300. Stop checking after <seconds>
  ignore_errors: yes # Errors do not stop execution

- name: Wait for ISE HTTPS
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 443
    state: started # started == Port is open
    delay: 0 # Default: 0. Seconds before first check
    sleep: 10 # Default: 1. Seconds between checks
    timeout: 3600 # Default: 300. Stop checking after <seconds>
  ignore_errors: yes # Errors do not stop execution

- name: Wait for ISE Admin GUI
  delegate_to: localhost
  ansible.builtin.uri:
    url: https://{{ ansible_host }}/admin/login.jsp
    method: GET
    follow_redirects: safe
    timeout: 10
    validate_certs: no
    return_content: no
  register: result
  until: result.status == 200
  retries: 500
  delay: 10
